### PR TITLE
Inspect AssertionError's without a full stack trace

### PR DESCRIPTION
**Pull request by sunesimonsen**
This will allow unchecked to work with Node's assert library.

### CODE REVIEW

**Comment by sunesimonsen** [comment]
> I guess we might want to display stacks from AssertionErrors coming from the code being tested, especially if they don’t carry a message? But I’m happy to wait and see if that’s a problem irl 👍

Do you think people will have assert's in production code? I know that is was a thing in the past, but I haven't seen that ever.

**Comment by sunesimonsen** [comment]
Let's roll with this for now, then we can correct it if it become a problem.

**Comment by sunesimonsen** [comment]
Released as unexpected-check@2.4.0

**Comment by papandreou** [comment]
> Do you think people will have assert's in production code?

Yes, that is definitely a thing: https://www.version2.dk/blog/5-kildetekstparanoia-4182

But yeah, let's wait and see.

**Pull request merged**
